### ISSUE TITLE
Q: Run external command / script based off email body

### ISSUE THREAD

**Issue by Strykar** [ThomasHabets/cmdg#103]
I am looking to trigger a shell script and fire some emails if the first line of an email from a specific sender matches a string.
Could I use cmdg to do this?

**Comment by ThomasHabets** [comment]
This sounds like it belongs as an apps script or something, no?

**Comment by Strykar** [comment]
Probably, the Gmail web interface lets me respond but that's restricted to email, I was hoping to trigger shell scripts.
What are you suggesting when you say apps script?

**Comment by ThomasHabets** [comment]
Shell scripting Apps script can't do, but it can do all the cloud things you can think of.

Maybe [this blog post](https://gmail.googleblog.com/2011/07/gmail-snooze-with-apps-script.html) could be a good start.

It depends what you need to do.

But if you want some IFTTT triggered by gmail, then maybe that's better implemented by some mail tail-thing with triggers. It could be put in this repo, and share libraries, but I don't see it bit built into the mail client.

**Comment by Strykar** [comment]
Perfect, thanks!
