### ISSUE TITLE
full name is not displayed on sent emails

### ISSUE THREAD

**Issue by pathcl** [ThomasHabets/cmdg#112]
I've just noticed if you send an email it won't include your full name. By default 'From' field is not included in the email body. There should be a way to include it by default. I'm on cmdg 1.02

**Comment by ThomasHabets** [comment]
Yeah, that's a bit ugly.

You could always provide your own From line when composing a message, but the default being just the address is a bit ugly.

I just pushed a commit that adds the option `-update_sender`. It's not the cleanest of solutions, but until there's a settings editor this'll let you set the default sender. Only needs be use once, and thereafter stored in the cloud. (meaning won't even need to be set on every client)
