### ISSUE TITLE
Release Workflow

### ISSUE THREAD

**Issue by sswastik02** [ThomasHabets/cmdg#117]
Release the Go package as a binary for various platforms using github actions

**Comment by sswastik02** [comment]
Hi @ThomasHabets ,
If this issue seems valid to you, I would like to work on this.

Thank you

**Comment by ThomasHabets** [comment]
Yeah, that sounds good. Is there any way to bake in the API key, without that API key being visible?

The stupid rules for Google API keys is that you can't share the key (so can't be in the source, presumably), but you can put it inside the binaries (where it of course could be extracted by anyone downloading the binary).

**Comment by ThomasHabets** [comment]
The code should be ready for hard coded API keys already, here: https://github.com/ThomasHabets/cmdg/blob/master/pkg/cmdg/configure.go#L24

**Comment by sswastik02** [comment]
> Yeah, that sounds good. Is there any way to bake in the API key, without that API key being visible?

Sure, we can use [Github Secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions) to store the API Key, and use it in the workflow.

**Comment by sswastik02** [comment]
> The code should be ready for hard coded API keys already, here: https://github.com/ThomasHabets/cmdg/blob/master/pkg/cmdg/configure.go#L24

Is there any other way of injecting API Keys apart from hardcoding it? If not I think we should work on that first and enter it (maybe) through environment variables or something like that.

@ThomasHabets, What are your thoughts on this ?

**Comment by ThomasHabets** [comment]
Not sure what you mean. Currently the API keys are user provided when the user runs `cmdg -configure`, and then stored in the config file. But this requires the user to create API keys, which sucks. I'd like a binary distribution to have them built in.

I just pushed a commit that makes sure that if the clientID is provided inside the binary, it's not then stored back into the config.

Do you mean can we give the compiler the keys in an environment variable at build time? Yes, now you can. E.g. with:

```
go build  -ldflags "-X main.InitID=blah -X main.InitSecret=blah2" ./cmd/cmdg 
```

**Comment by ThomasHabets** [comment]
Of course with `${CLIENTID?}` or something instead of `blah`, to pick up the value.

If you're looking at building for windows, it's instead `%CLIENTID%`.

**Comment by sswastik02** [comment]
> Not sure what you mean. Currently the API keys are user provided when the user runs `cmdg -configure`, and then stored in the config file. But this requires the user to create API keys, which sucks. I'd like a binary distribution to have them built in.
> 
> I just pushed a commit that makes sure that if the clientID is provided inside the binary, it's not then stored back into the config.
> 
> Do you mean can we give the compiler the keys in an environment variable at build time? Yes, now you can. E.g. with:
> 
> ```
> go build  -ldflags "-X main.InitID=blah -X main.InitSecret=blah2" ./cmd/cmdg 
> ```

This seems interesting will try this in the workflow
Thank you.

**Comment by sswastik02** [comment]
Hi @ThomasHabets ,
I noticed one thing, `go` errors while building with version `1.14`. Upgrading to `1.20` has no problem and builds successfully.
Is it ok if I bump the version as well while sending the PR? or would you like to have it done separately?

**Comment by sswastik02** [comment]
Hi @ThomasHabets, 
Another issue I encountered is that Go won't build for Windows due to the usage of UNIX-specific code [here](https://github.com/ThomasHabets/cmdg/blob/7d5bb2d231fa03f5fe299d17de1dd329ca341f55/pkg/input/input.go#L16). Hence, I think it's best to skip the build for Windows for now.

**Comment by ThomasHabets** [comment]
Go version: Could you try the versions between 1.15 and 1.20, to see which one is enough? Debian has 1.19 only, it seems, so 1.20 may be too new to assume.

(yes, installing the newest Go version is easy, but still it'd be nice to not require it unless needed)

Go version change can be in the same PR, but keep it in a separate git commit.

**Comment by ThomasHabets** [comment]
I can check the range of Go versions too if you prefer, later today.

**Comment by ThomasHabets** [comment]
I just checked. Go 1.18 is the minimum version. Fixed.

**Comment by sswastik02** [comment]
> I just checked. Go 1.18 is the minimum version. Fixed.

Thanks @ThomasHabets, for fixing the minimum required go version.
