### ISSUE TITLE
buggy scrolling on cmd.exe

### ISSUE THREAD

**Issue by icewyvrn** [ThomasHabets/cmdg#118]
is it possible to fix?

**Comment by ThomasHabets** [comment]
Please be WAY more specific.

Anything's possible to fix. But I'm not going to set up a window build environment only to not find what you're talking about.

Does it work in powershell, or whatever windows recommends nowadays?

**Comment by icewyvrn** [comment]
here's what i am talking about: 
![Screenshot (283)](https://github.com/ThomasHabets/cmdg/assets/41411360/f021bb28-2f42-49f8-b376-7f098d5cfc39)
it shows those text at the bottom when moving the selection

same problem in powershell

but i use mintty and it works normally, probably works in the new windows terminal too.

**Comment by ThomasHabets** [comment]
I just added a flag to disable atomic updates, could you try the current version with `-atomic_screen_updates=false`, to see if it fixes it?

**Comment by ThomasHabets** [comment]
For future reference, this was added in 6935b1d2230b24c1d87e44e2b49e9210b9720e69

**Comment by icewyvrn** [comment]
fixed, thanks!
