### ISSUE TITLE
to download attached file from the mail using script

### ISSUE THREAD

**Issue by vadirajks** [ThomasHabets/cmdg#123]
Hi Team,
I would like to use this in my script to download attached file from the mail,  based on the mail search pattern referring to mail subject  and there corresponding date to filter if needed. Please let me know if it is possible.
Thanks you very much for helping all this to others.

**Comment by ThomasHabets** [comment]
It's possible, but I don't think it's appropriate for an email client. Sounds very specific.

Normally I'd say just send a PR, but in this case Google is being an asshole about API keys, and want to be really careful about the use case for the API key. So I think this may belong in another project.

**Comment by ThomasHabets** [comment]
It shouldn't be too hard to do, though. The GMail API is well documented.
