### ISSUE TITLE
Install issues on Fedora 27

### ISSUE THREAD

**Issue by sferich888** [ThomasHabets/cmdg#56]
I am new to golang, but I believe that this is a "product"/"project" specific issue. 
~~~
go get github.com/ThomasHabets/cmdg
# github.com/ThomasHabets/drive-du/lib
.go_path/src/github.com/ThomasHabets/drive-du/lib/auth.go:80:15: undefined: transport
~~~

Fresh Install of Fedora 27, following: https://developer.fedoraproject.org/tech/languages/go/go-installation.html

**Comment by ThomasHabets** [comment]
Oops. Don't know how that happened. Do a `git pull` inside `src/github.com/ThomasHabets/drive-du` and see if that helps.
