### ISSUE TITLE
accented utf8 characters broken

### ISSUE THREAD

**Issue by ptica** [ThomasHabets/cmdg#57]
sbjs list looks like this:
![screen shot 2018-08-23 at 13 20 19](https://user-images.githubusercontent.com/169873/44522601-60fa5c80-a6d7-11e8-8f43-e95764064e61.png)

my LC_ALL=cs_CZ.UTF-8
email bodies are also broken

**Comment by ThomasHabets** [comment]
I haven't looked at this in a while, but I think it could be limitations in ncurses wrapper.

Dup of https://github.com/ThomasHabets/cmdg/issues/21

**Comment by ThomasHabets** [comment]
This should be correct now, after rewrite.
