### ISSUE TITLE
Work around the different signatures of syscall.Select

### ISSUE THREAD

**Issue by RakibFiha** [ThomasHabets/cmdg#61]
I got this error when I ran

```
go build github.com/ThomasHabets/cmdg/cmd/cmdg

src/github.com/ThomasHabets/cmdg/pkg/input/input.go:117:5: cannot use [16]int64 literal (type [16]int64) as type [32]int32 in field value
src/github.com/ThomasHabets/cmdg/pkg/input/input.go:119:11: assignment mismatch: 2 variables but syscall.Select returns 1 values
```

**Comment by ThomasHabets** [comment]
Do you have an old version of Go?

What's the output of `go version`?

**Comment by RakibFiha** [comment]
go version go1.12 darwin/amd64

**Comment by ThomasHabets** [comment]
Huh. Yeah [that is a different type](https://github.com/golang/go/blob/master/src/syscall/ztypes_darwin_amd64.go#L292). I'm not sure how to make that portable. You can fix it for you by hcanging the [16] to [32] for the first error, and then for the second error change the code to:

```
n, err := 1, syscall.Select(fd+1, &fds, &syscall.FdSet{}, &syscall.FdSet{}, &syscall.Timeval{
				Sec:  0,
				Usec: 50000,
			})
```

**Comment by cutzenfriend** [comment]
> Huh. Yeah [that is a different type](https://github.com/golang/go/blob/master/src/syscall/ztypes_darwin_amd64.go#L292). I'm not sure how to make that portable. You can fix it for you by changing the [16] to [32] for the first error, and then for the second error change the code to:
> 
> ```
> n, err := 1, syscall.Select(fd+1, &fds, &syscall.FdSet{}, &syscall.FdSet{}, &syscall.Timeval{
> 				Sec:  0,
> 				Usec: 50000,
> 			})
> ```

Tried you fix. Only works for the second error. Any ideas?

`➜  go go build github.com/ThomasHabets/cmdg/cmd/cmdg
# github.com/ThomasHabets/cmdg/pkg/input
src/github.com/ThomasHabets/cmdg/pkg/input/input.go:117:5: cannot use [32]int64 literal (type [32]int64) as type [32]int32 in field value`

**Comment by ThomasHabets** [comment]
Correction: change the `[16]int64` to `[32]int32` for the first error.

Keeping this bug open to track making this build out of the box on mac.

**Comment by rpietro** [comment]
@ThomasHabets not sure if my error is related to @RakibFiha , check this out:

```
➜  ~ go build github.com/ThomasHabets/cmdg/cmd/cmdg
can't load package: package github.com/ThomasHabets/cmdg/cmd/cmdg: cannot find package "github.com/ThomasHabets/cmdg/cmd/cmdg" in any of:
        /usr/lib/go/src/github.com/ThomasHabets/cmdg/cmd/cmdg (from $GOROOT)
        /home/rpietro/go/src/github.com/ThomasHabets/cmdg/cmd/cmdg (from $GOPATH)
➜  ~ go version                                    
go version go1.12.7 linux/amd64

```

Thoughts?

**Comment by ThomasHabets** [comment]
@rpietro no, that's not related. Looks like you skipped the step `go get github.com/ThomasHabets/cmdg` from the install instructions.

**Comment by ThomasHabets** [comment]
For this issue: I encountered the same problem on OpenBSD. So likely this `syscall.Select` issue affects all BSDs.

**Comment by ThomasHabets** [comment]
I've filed https://github.com/golang/go/issues/34458 for the Go team on how to solve this.
