### ISSUE TITLE
MacOS uses int32 nanoseconds for unix.Select

### ISSUE THREAD

**Issue by hexindent** [ThomasHabets/cmdg#64]
I tried to build cmdg on macOS Mojave 10.14.6 and I ran into this problem. I have no idea what went wrong. Thanks for any help!

```
$ go get github.com/ThomasHabets/cmdg
$ package github.com/ThomasHabets/cmdg: no Go files in go/src/github.com/ThomasHabets/cmdg
$ go build github.com/ThomasHabets/cmdg/cmd/cmdg
$ # github.com/ThomasHabets/cmdg/pkg/input
src/github.com/ThomasHabets/cmdg/pkg/input/input.go:131:3: cannot use timeout.Nanoseconds() / 1000 % 1e+06 (type int64) as type int32 in field value
```

**Comment by ThomasHabets** [comment]
Sigh. Again the Go maintainers create nonportable code.

Try changing the line:

```
Usec: (timeout.Nanoseconds() / 1000) % 1e6,
```

into:

```
Usec: int32((timeout.Nanoseconds() / 1000) % 1e6),
```

I'll work around it with the next few days.

The first error ("no Go files in") is not really an error.

**Comment by ThomasHabets** [comment]
There, should be fixed now. Please let me know if it still doesn't work.

**Comment by hexindent** [comment]
Thank you very much! The issue went away and the build is successful.

**Comment by alicaccs** [comment]
A similar error occured when trying to build cmdg 1.04 with go 1.20 on i386 32bit machine.
```
# github.com/ThomasHabets/cmdg/pkg/input
pkg/input/input.go:135:8: cannot use timeout.Nanoseconds() / 1e9 (value of type int64) as int32 value in struct literal

```

**Comment by ThomasHabets** [comment]
Sigh. I'm starting to regret trying to write a portable program in Go. :-(

**Comment by ThomasHabets** [comment]
@alicaccs I just pushed a commit that should fix this, please try at head.
