### ISSUE TITLE
Made a Homebrew formula for macOS

### ISSUE THREAD

**Issue by cutzenfriend** [ThomasHabets/cmdg#66]
Hi there, I created a Homebrew [(Package Manager for macOS)](https://brew.sh/) formula for easier installation on macOS.

`brew tap cutzenfriend/homebrew-cmdg`
`brew install cmdg`

It would be great if you could add this to the readme. If you want I could try to get this into the homebrew core :)

**Comment by ThomasHabets** [comment]
Done in https://github.com/ThomasHabets/cmdg/commit/d2af16d823113af129a8ecf9c221269654481ac8

**Comment by ThomasHabets** [comment]
Thanks! Yeah, having it in core would be cool. I don't know much about Macs and homebrew though, so probably can't help much.
