### ISSUE TITLE
Can't start cmdg after configuration

### ISSUE THREAD

**Issue by ThatOneCalculator** [ThomasHabets/cmdg#69]
I did all of the configuration with the ClientID/Client Secret/Web request, it looked good, then I ran `cmdg` and got

```
INFO[0000] cmdg 1.00+
FATA[0000] You need to set the PAGER environment variable. When in doubt, set to 'less'.```

**Comment by ThomasHabets** [comment]
Before starting cmdg, set environment variables to indicate some programs.

E.g.:

```
export PAGER=less
export VISUAL=emacs
```
