### ISSUE TITLE
Add the "delete marked message" feature

### ISSUE THREAD

**Issue by cyruz-git** [ThomasHabets/cmdg#72]
It would be nice to have the possibility to delete messages

**Comment by ThomasHabets** [comment]
Huh. I seem to have forgotten about that since I tend to never delete email. Should be easy enough.

**Comment by ThomasHabets** [comment]
Note that `d` moves the message to trash. ["Deleting" in gmail API means irrevocably delete the message](https://developers.google.com/gmail/api/v1/reference/users/messages/delete), and requires further oauth permissions that cmdg is currently not asking for. This is deliberate to protect against bugs in cmdg.

So if you need to have the messages really be deleted, currently you have to use the web UI to empty the trash.

**Comment by cyruz-git** [comment]
Wonderful, self deletion will take care of the rest. Thank you :)
