### ISSUE TITLE
View the "All mail" label?

### ISSUE THREAD

**Issue by Salvar** [ThomasHabets/cmdg#87]
Is that even a label? I somehow cannot access archived mails anywhere, via any label avilable to me. Selecting "Show in IMAP" in Manage Labels Gmail UI doesn't seem to do anything.

**Comment by ThomasHabets** [comment]
I thought an empty search did this, but seems I special cased that. I just removed that special casing, so searching for an empty string now shows all mail.

Reopening, in case you see need to simulate a fake "All Mail" label, since indeed, it's not a real label.

**Comment by ThomasHabets** [comment]
Workaround if you don't want to rebuild: You can just search for a single space. All mail will match that, presumably.

**Comment by Salvar** [comment]
That works for me, thanks for clarifying!

**Comment by ThomasHabets** [comment]
Thanks for reporting/asking. :-)
