### ISSUE TITLE
cant use emacs as editor on CLI

### ISSUE THREAD

**Issue by tshrinivasan** [ThomasHabets/cmdg#89]
The is my editor config on environment.

1. 
$ env | grep -i editor
EDITOR=/usr/bin/emacsclient

But when I click "a" to reply, it is giving the below error.

Failed to replyAll: editor "/usr/bin/emacsclient" failed: exit status 1                                                                                       
Press [enter] to continue                                                                                                                                     
————————————————————————————————

2.
If i change the editor to 

$ env | grep -i editor
EDITOR=/usr/bin/emacs

It opens a brand new emacs GUI.

I want to use the "emacs -nw" as a CLI editor so that I can reply on the terminal itself.

3.

$ env | grep -i editor
EDITOR=/usr/bin/emacs -nw

$ grep "EDITOR" .bashrc
export EDITOR="/usr/bin/emacs -nw" 

for this, receiving below error, on reply 

Failed to replyAll: failed to start editor "/usr/bin/emacs -nw": fork/exec /usr/bin/emacs -nw: no such file or directory                                      
Press [enter] to continue 

Please check for this on and guide on what is the variable to use with EDITOR to use "emacs -nw" to reply for emails.

"emacs -nw" is the command to invoke emacs on CLI.

**Comment by ThomasHabets** [comment]
Two short term workarounds:

1. Set EDITOR to a script that does `exec emacs -nw "$@"`
2. Install an emacs that doesn't have X support, like in Debian `emacs-nox`.

I'll play around with emacsclient, to see if there's something that can be fixed. I use emacs, but not emacsserver/client, myself.

**Comment by tshrinivasan** [comment]
Thanks for the reply.

I did the below

$ cat /usr/bin/emacs-cli 
#!/bin/bash
/usr/bin/emacs -Q -nw $@

$ grep -i editor ~/.bashrc
export EDITOR="/usr/bin/emacs-cli" 


It works fine now on CLI.

Ignore the emacsclient. For the CLI mail client, CLI editor is enough.

Thanks for your great works.

**Comment by ThomasHabets** [comment]
For the wrapper script I would recommend `exec /usr/bin/emacs -Q -nw "$@"`, exactly. `exec` to not have a bash intermediate process wasting memory, and quotes around `$@` to have it correctly handle spaces.

Not that it's a problem in this case, but in the general case it's better.

**Comment by 3ruce** [comment]
Using spacemacs, adding this line in a script worked for me

`exec /usr/bin/emacs -nw "$@"`

I suspect the -Q removed all the spacemacs stuff!

**Comment by 3ruce** [comment]
This works even better via the emacs daemon...

```
#!/bin/sh

exec /usr/bin/emacsclient -t -a "" "$1"
```
