### ISSUE TITLE
emacs , gmail, oauth2

### ISSUE THREAD

**Issue by tshrinivasan** [ThomasHabets/cmdg#90]
I am trying to read gmail with emacs using gnus/notmuch etc.

my office gmail has only oauth2, these above and mutt, neomutt are not working with oauth2.

Good to see that cmdg uses oauth2 and I can read email on terminal.

If possible, get a solution for emacs or mutt to read gmail with oauth2

Thanks for the great work.

**Comment by ThomasHabets** [comment]
It sounds like what you need is an imap-gmailapi proxy, which I think would have to be a separate project.
