### ISSUE TITLE
Loading contacts: googleapi: Error 403: People API has not been used

### ISSUE THREAD

**Issue by hacker-DOM** [ThomasHabets/cmdg#93]
I get the following error on my first run of the program after `cmdg -configure`

(X is my project number)

```
❯ cmdg
INFO[0000] cmdg 1.02                                    
INFO[0000] Connected                                    
FATA[0001] Loading contacts: googleapi: Error 403: People API has not been used in project X before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=X then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured 
```

The Peoples Api in the url has a button showing "Disable API", implying that is is active. Needless to say, I've waited over 2 hours

**Comment by ThomasHabets** [comment]
That's strange. Have you tried turning it off and on again? :-)

The API, that is. Try disabling and re-enabling.

This is what the page looks like for my project:

![enabled-api2](https://user-images.githubusercontent.com/6056/196131413-1fdac36b-f5cf-426d-9e2c-59f4c846a636.png)


There's also https://console.cloud.google.com/apis/library/people.googleapis.com?project=X which looks like this for me:

![enabled-api](https://user-images.githubusercontent.com/6056/196130598-e59ff363-2f59-4ad0-88f2-1ab9735f167a.png)

**Comment by hacker-DOM** [comment]
Yup, I got it work in the end :-)
