### ISSUE TITLE
new user, few questions

### ISSUE THREAD

**Issue by kurokirasama** [ThomasHabets/cmdg#95]
Hey, I just found this and it seems awesome.  A few questions:

1. Can I change the from address when replying?
2. Related to the first one, gmail has a feature that when receiving email from multiple accounts, and you also have them set available to send email with other account, you reply from the address the email was sent to... Is there an option to enable that?
3. When searching, how do I select a result in the list? For instance when composing and email and filling the `to` field
4. Is there a way to customize colors? Like for instance, I would like that the info about from, to, subject, etc, to be of a different color
5. Can I change some keybindings?

Regards,

**Comment by ThomasHabets** [comment]
1. Yeah you can just add a header `From: mysource@example.com` in the compose editor.
2. Make sure to reply from the same address as was sent to? No, that's not implemented.
3. Search in all places (also file picker for attachments) is search-as-you-type, and then you can use Ctrl-N and Ctrl-P to navigate the options. I just realized I never added support for arrow keys too. Will do.
4. Nope, not implemented.
5. Keybindings are not configurable, currently. You'd have to edit the source.

**Comment by kurokirasama** [comment]
Cool!!! Thanks for your response. I was using alpine as my tui email client but this has so much utility.

**Comment by ThomasHabets** [comment]
Happy to hear it.

I just pushed a commit to allow arrow keys in the selection boxes. For the rest you can file issues with individual feature requests. Can't promise I'll get to them, but then they're tracked and makes it easier to accept well written patches.
