### ISSUE TITLE
question: how to easily return to the beginning of the email list  or the first line of a message?

### ISSUE THREAD

**Issue by kurokirasama** [ThomasHabets/cmdg#98]

**Comment by ThomasHabets** [comment]
Pressing the Home button should do it it both cases.

**Comment by kurokirasama** [comment]
@ThomasHabets It doesn't work for me...

**Comment by ThomasHabets** [comment]
If you start `cmdg` with `-log cmdg.log`, and press `Home` in the message list view you should see something like this in `cmdg.log`:

```
time="2022-11-26T17:19:46Z" level=info msg="MessageListView got unknown key \"\\x1b[4~\" [27 91 52 126]"
```

What exactly do you see? The example I quote here is pressing `End`, since `Home` works for me.

**Comment by kurokirasama** [comment]
Here's the log. 
I only opened cmdg, down arrow key 10 times, home button 3 times, end button 3 times, close.
[cmdg.log](https://github.com/ThomasHabets/cmdg/files/10096847/cmdg.log)

**Comment by ThomasHabets** [comment]
Thanks for the log. Just pushed a commit that should fix it.

**Comment by kurokirasama** [comment]
thank! Now it works!
